graph TD
    "Dtos" --> "CreateBookingDto"
    "Dtos" --> "UpdateRoleDto"
    "Dtos" --> "CreateUserDto"
    "Dtos" --> "AvailablePermissionDto"
    "Dtos" --> "BookingDto"
    "Dtos" --> "AvailabilityDto"
    "Dtos" --> "LoginDto"
    "Dtos" --> "DateOverrideDto"
    "Dtos" --> "RoleDto"
    "Dtos" --> "UserDto"
    "Dtos" --> "WeeklyScheduleDto"
    "Dtos" --> "CreateRoleDto"
    "admin" --> "schedule"
    "admin" --> "login"
    "admin" --> "users"
    "admin" --> "roles"
    "admin" --> "bookings"
    "admin" --> "index"
    "Controllers" --> "DateOverrideController"
    "Controllers" --> "ScheduleController"
    "Controllers" --> "AvailabilityController"
    "Controllers" --> "UserController"
    "Controllers" --> "RoleController"
    "Controllers" --> "AuthController"
    "Controllers" --> "BookingController"
    "Migrations" --> "20260506121253_InitalCreate"
    "Migrations" --> "AppDbContextModelSnapshot"
    "Migrations" --> "20260506121253_InitalCreate.Designer"
    "Entities" --> "DateOverride"
    "Entities" --> "User"
    "Entities" --> "Booking"
    "Entities" --> "RolePermission"
    "Entities" --> "Role"
    "Entities" --> "WeeklySchedule"
    "js" --> "auth"
    "js" --> "app"
    "js" --> "permissions"
    "js" --> "site"
    "Managers" --> "RoleManager"
    "Managers" --> "DateOverrideManager"
    "Managers" --> "AuthManager"
    "Managers" --> "BookingManager"
    "Managers" --> "TokenManager"
    "Managers" --> "ScheduleManager"
    "Managers" --> "UserManager"
    "Managers" --> "AvailabilityManager"
    "Enums" --> "UserRole"
    "Enums" --> "BookingStatus"
    "wwwroot" --> "index"
    "net10.0" --> "VechileCleaningAPI.AssemblyInfo"
    "net10.0" --> ".NETCoreApp,Version=v10.0.AssemblyAttributes"
    "net10.0" --> "VechileCleaningAPI.GlobalUsings.g"
    "net10.0" --> "VechileCleaningAPI.AssemblyInfo"
    "net10.0" --> "CleaningPlatformAPI.AssemblyInfo"
    "net10.0" --> "CleaningPlatformAPI.GlobalUsings.g"
    "net10.0" --> "CleaningPlatformAPI.MvcApplicationPartsAssemblyInfo"
    "net10.0" --> "VechileCleaningAPI.MvcApplicationPartsAssemblyInfo"
    "net10.0" --> "VechileCleaningAPI.GlobalUsings.g"
    "net10.0" --> ".NETCoreApp,Version=v10.0.AssemblyAttributes"
    "CleaningPlatformAPI" --> "Program"
    "Authorization" --> "PermissionHandler"
    "Authorization" --> "PermissionRequirement"
    "Common" --> "OperationResult"
    "Common" --> "PermissionKeys"
    "CleaningPlatform" --> "Index"
    "css" --> "style"
    "css" --> "site"
    "css" --> "style2"
    "Data" --> "AppDbContext"
