// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VechileCleaningAPI.Data;

#nullable disable

namespace VechileCleaningAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506121253_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VechileCleaningAPI.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.DateOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EndHour")
                        .HasColumnType("int");

                    b.Property<bool>("IsFullyClosed")
                        .HasColumnType("bit");

                    b.Property<int?>("StartHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DateOverrides");
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsProtected = true,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsProtected = false,
                            Name = "Dispatcher"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsProtected = false,
                            Name = "Cleaner"
                        });
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionKey = "pages.daily",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionKey = "pages.bookings",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionKey = "pages.schedule",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionKey = "pages.users",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionKey = "pages.roles",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionKey = "actions.booking.updateStatus",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionKey = "actions.schedule.edit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionKey = "actions.override.manage",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionKey = "actions.user.create",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionKey = "actions.user.toggleActive",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionKey = "actions.role.manage",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionKey = "pages.daily",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            PermissionKey = "pages.bookings",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            PermissionKey = "pages.schedule",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            PermissionKey = "actions.booking.updateStatus",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            PermissionKey = "actions.schedule.edit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            PermissionKey = "actions.override.manage",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            PermissionKey = "pages.daily",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 19,
                            PermissionKey = "pages.bookings",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Owner",
                            PasswordHash = "$2y$10$qZKh.FlEZrHNSyAcazlNdOyBMHA.SJSfnLDoPtuFKt9Mrj99tdNEe",
                            RoleName = "Owner",
                            Surname = "User",
                            Username = "owner"
                        });
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("EndHour")
                        .HasColumnType("int");

                    b.Property<int>("StartHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeeklySchedules");
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.RolePermission", b =>
                {
                    b.HasOne("VechileCleaningAPI.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
