// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VechileCleaningAPI.Data;

#nullable disable

namespace VechileCleaningAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504173300_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VechileCleaningAPI.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.SlotOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Hour")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SlotOverrides");
                });

            modelBuilder.Entity("VechileCleaningAPI.Entities.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("int");

                    b.Property<int>("EndHour")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("StartHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeeklySchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 0,
                            DefaultCapacity = 2,
                            EndHour = 17,
                            IsClosed = true,
                            StartHour = 8
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            DefaultCapacity = 2,
                            EndHour = 17,
                            IsClosed = false,
                            StartHour = 8
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 2,
                            DefaultCapacity = 2,
                            EndHour = 17,
                            IsClosed = false,
                            StartHour = 8
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 3,
                            DefaultCapacity = 2,
                            EndHour = 17,
                            IsClosed = false,
                            StartHour = 8
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 4,
                            DefaultCapacity = 2,
                            EndHour = 17,
                            IsClosed = false,
                            StartHour = 8
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 5,
                            DefaultCapacity = 2,
                            EndHour = 17,
                            IsClosed = false,
                            StartHour = 8
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 6,
                            DefaultCapacity = 2,
                            EndHour = 13,
                            IsClosed = false,
                            StartHour = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
